<?php

namespace App\Game\Engine;

use App\Game\TurnSlot;
use App\Game\Verb;

/**
 * A pre-validated verb + target + modifier bundle. Cards are generated by
 * the CardComposer from the current scene — never hand-listed, never free
 * text. The id is deterministic so a submission can be checked against the
 * stored offer.
 */
class ActionCard
{
    /**
     * @param  array{type:string,id:int|null,name:string}|null  $target
     * @param  list<array{meter:string,amount:int}>  $cost
     * @param  list<array{key:string,label:string,options:list<array{value:string,label:string}>}>  $modifiers
     * @param  array{key:string,edge_label:string,complication_label:string}|null  $bargain  The
     *                                                                                       deal this card is, when it is one: a named edge on the arithmetic
     *                                                                                       traded for a named complication the engine applies whether the roll
     *                                                                                       lands or not. A bargain is always offered BESIDE its plain sibling,
     *                                                                                       which is why the key has to reach id() — same verb, same target,
     *                                                                                       different card.
     */
    public function __construct(
        public readonly TurnSlot $slot,
        public readonly string $verb,
        public readonly string $label,
        public readonly string $description,
        public readonly ?array $target = null,
        public readonly ?string $capability = null,
        public readonly string $risk = 'safe', // safe | risky | degraded
        public readonly array $cost = [],
        public readonly array $modifiers = [],
        public readonly bool $composed = false,
        public readonly ?array $bargain = null,
    ) {}

    /**
     * The same beat, offered in a different position in the turn.
     *
     * Every one of the player's three picks offers the whole list, so a beat is
     * composed once and then stands in all three. The slot is part of id(), so
     * the three copies are three distinct, individually validated cards rather
     * than one card the submission could point at from anywhere.
     */
    public function withSlot(TurnSlot $slot): self
    {
        return $slot === $this->slot ? $this : new self(
            slot: $slot,
            verb: $this->verb,
            label: $this->label,
            description: $this->description,
            target: $this->target,
            capability: $this->capability,
            risk: $this->risk,
            cost: $this->cost,
            modifiers: $this->modifiers,
            composed: $this->composed,
            bargain: $this->bargain,
        );
    }

    public function id(): string
    {
        return substr(hash('sha256', implode('|', [
            $this->slot->value,
            $this->verb,
            $this->capability ?? '-',
            $this->target['type'] ?? '-',
            $this->target['id'] ?? '-',
            $this->risk,
            // Without this the deal and the honest version of the same beat
            // would collapse onto one id, and a submission could not say which
            // of the two the player actually committed to.
            $this->bargain['key'] ?? '-',
        ])), 0, 16);
    }

    /**
     * @param  array<string,mixed>  $conditions  What is already true of the
     *                                           scene as this card is offered. The forecast
     *                                           prices the card against it.
     */
    public function toArray(array $conditions = []): array
    {
        return [
            'id' => $this->id(),
            'slot' => $this->slot->value,
            'verb' => $this->verb,
            // Where this card sits on the board, decided by the engine's own
            // catalog. The client never re-derives it: a second copy of the
            // vocabulary living in a Vue file is exactly how a verb the engine
            // added last week ends up filed under "everything else".
            'family' => Verb::familyOf($this->verb)->value,
            'verb_label' => Verb::labelOf($this->verb),
            'label' => $this->label,
            'description' => $this->description,
            'target' => $this->target,
            'capability' => $this->capability,
            'risk' => $this->risk,
            'cost' => $this->cost,
            'modifiers' => $this->modifiers,
            'composed' => $this->composed,
            // Both halves of the deal, in the player's words: what it buys and
            // what it costs. The forecast below already carries the edge as an
            // itemized part, so the two readings can never disagree.
            'bargain' => $this->bargain,
            'forecast' => $this->forecast($conditions),
        ];
    }

    /**
     * What this card costs in difficulty, quoted before it is chosen.
     *
     * A turn commits the instant it is submitted — there is no going back to
     * re-pick once the number turns out to have been 18 — so a card that does
     * not price itself is a card the player is guessing at. Every figure here
     * comes from the same Odds ledger the resolver will read, per stance, so
     * the forecast and the roll cannot drift apart.
     *
     * `conditions` is what is true RIGHT NOW: high ground already held counts,
     * a set-up beat the player is about to choose does not — that one is
     * quoted on its own card, as a grant, and the page adds it up as the plan
     * is assembled.
     *
     * @return array{rolls:bool,difficulty:int,band:string,parts:list<array{label:string,amount:int}>,stances:array<string,int>,bonus:int,bonus_parts:list<array{label:string,amount:int}>,grant:?array,endeavor:?string,thread:?string}
     */
    /**
     * This card in the shape Odds reads it — the same shape the resolver hands
     * over when the beat comes due, so the forecast and the die are answering
     * questions about the same object.
     *
     * The capability travels with it because some of the ledger prices the
     * body, not the verb: a leap taken as a `cross` and a leap taken as an
     * `ascend` meet the same wind. So does the deal, which is one more itemized
     * reason the number is what it is.
     *
     * @return array{verb:string,risk:string,capability:?string,target:?array,slot:string,bargain:?array}
     */
    public function oddsCard(): array
    {
        return [
            'verb' => $this->verb,
            'risk' => $this->risk,
            'capability' => $this->capability,
            'target' => $this->target,
            'slot' => $this->slot->value,
            'bargain' => $this->bargain,
        ];
    }

    private function forecast(array $conditions): array
    {
        $card = $this->oddsCard();

        $grant = Odds::grant($this->verb);

        // What this beat moves toward, when an endeavor is open and names its
        // verb. Same shape of promise as a grant: it is quoted before the
        // commit, off the clock's own row — the very list the resolver's tick
        // reads — so a card can never advertise progress the beat will not pay.
        $endeavor = $conditions['endeavor'] ?? null;
        $advances = ($endeavor !== null && in_array($this->verb, $endeavor['verbs'] ?? [], true))
            ? $endeavor['name'] : null;

        // And whose small story this beat would help along, when the player has
        // discovered one. Same promise, same source — the thread's own row —
        // with one deliberate difference from the endeavor above: a roll-free
        // beat may carry it. What a search is gated on is EXPOSURE rather than
        // a die, and `examine` casts none while turning things up all the same.
        $helps = self::helpsThread($conditions['thread'] ?? null, $this->verb, $this->target);

        // Odds decides whether this card casts a die — verb first, and then the
        // one card-level exception: an uncontested way out is a step through a
        // door, not a test. The resolver asks the same question of the same
        // table, so "Certain" here is certain there.
        if (Odds::certain($card, $conditions)) {
            return [
                'rolls' => false,
                'difficulty' => 0,
                'band' => 'Certain',
                'parts' => [],
                'stances' => [],
                'bonus' => 0,
                'bonus_parts' => [],
                'grant' => $grant,
                // A beat that casts no die can never tick a clock, so a
                // roll-free card never promises one either.
                'endeavor' => null,
                'thread' => $helps,
            ];
        }

        $stances = [];
        foreach (['balanced', 'cautious', 'bold'] as $stance) {
            $stances[$stance] = Odds::difficulty($card, $stance, $conditions)['value'];
        }

        $balanced = Odds::difficulty($card, 'balanced', $conditions);
        $bonus = Odds::bonus($conditions, $this->verb, $this->slot->value, $this->bargain['key'] ?? null);

        return [
            'rolls' => true,
            'difficulty' => $balanced['value'],
            'band' => Odds::band($balanced['value']),
            'parts' => $balanced['parts'],
            'stances' => $stances,
            'bonus' => $bonus['value'],
            'bonus_parts' => $bonus['parts'],
            'grant' => $grant,
            'endeavor' => $advances,
            'thread' => $helps,
        ];
    }

    /**
     * Whose want this beat would help along, or null.
     *
     * The forecast quotes the thread's stored verb list and — where the kind
     * names one thing — the stored target, so a card can never advertise
     * progress the resolver's own check would refuse.
     *
     * @param  array{name:string,verbs:list<string>,target_id:?int}|null  $thread
     * @param  array{type:string,id:int|null,name:string}|null  $target
     */
    private static function helpsThread(?array $thread, string $verb, ?array $target): ?string
    {
        if ($thread === null || ! in_array($verb, $thread['verbs'] ?? [], true)) {
            return null;
        }

        $named = $thread['target_id'] ?? null;

        if ($named !== null
            && (($target['type'] ?? null) !== 'feature' || (int) ($target['id'] ?? 0) !== (int) $named)) {
            return null;
        }

        return $thread['name'];
    }

    public static function fromArray(array $data): self
    {
        return new self(
            slot: TurnSlot::from($data['slot']),
            verb: $data['verb'],
            label: $data['label'],
            description: $data['description'],
            target: $data['target'] ?? null,
            capability: $data['capability'] ?? null,
            risk: $data['risk'] ?? 'safe',
            cost: $data['cost'] ?? [],
            modifiers: $data['modifiers'] ?? [],
            composed: $data['composed'] ?? false,
            bargain: $data['bargain'] ?? null,
        );
    }
}
