<?php

namespace App\Game\Engine;

use App\Game\TurnSlot;
use App\Game\Verb;

/**
 * A pre-validated verb + target + modifier bundle. Cards are generated by
 * the CardComposer from the current scene — never hand-listed, never free
 * text. The id is deterministic so a submission can be checked against the
 * stored offer.
 */
class ActionCard
{
    /**
     * @param  array{type:string,id:int|null,name:string}|null  $target
     * @param  list<array{meter:string,amount:int}>  $cost
     * @param  list<array{key:string,label:string,options:list<array{value:string,label:string}>}>  $modifiers
     * @param  array{key:string,edge_label:string,complication_label:string}|null  $bargain  The
     *                                                                                       deal this card is, when it is one: a named edge on the arithmetic
     *                                                                                       traded for a named complication the engine applies whether the roll
     *                                                                                       lands or not. A bargain is always offered BESIDE its plain sibling,
     *                                                                                       which is why the key has to reach id() — same verb, same target,
     *                                                                                       different card.
     */
    public function __construct(
        public readonly TurnSlot $slot,
        public readonly string $verb,
        public readonly string $label,
        public readonly string $description,
        public readonly ?array $target = null,
        public readonly ?string $capability = null,
        public readonly string $risk = 'safe', // safe | risky | degraded
        public readonly array $cost = [],
        public readonly array $modifiers = [],
        public readonly bool $composed = false,
        public readonly ?array $bargain = null,
    ) {}

    public function id(): string
    {
        return substr(hash('sha256', implode('|', [
            $this->slot->value,
            $this->verb,
            $this->capability ?? '-',
            $this->target['type'] ?? '-',
            $this->target['id'] ?? '-',
            $this->risk,
            // Without this the deal and the honest version of the same beat
            // would collapse onto one id, and a submission could not say which
            // of the two the player actually committed to.
            $this->bargain['key'] ?? '-',
        ])), 0, 16);
    }

    /**
     * @param  array<string,mixed>  $conditions  What is already true of the
     *                                           scene as this card is offered. The forecast
     *                                           prices the card against it.
     */
    public function toArray(array $conditions = []): array
    {
        return [
            'id' => $this->id(),
            'slot' => $this->slot->value,
            'verb' => $this->verb,
            // Where this card sits on the board, decided by the engine's own
            // catalog. The client never re-derives it: a second copy of the
            // vocabulary living in a Vue file is exactly how a verb the engine
            // added last week ends up filed under "everything else".
            'family' => Verb::familyOf($this->verb)->value,
            'verb_label' => Verb::labelOf($this->verb),
            'label' => $this->label,
            'description' => $this->description,
            'target' => $this->target,
            'capability' => $this->capability,
            'risk' => $this->risk,
            'cost' => $this->cost,
            'modifiers' => $this->modifiers,
            'composed' => $this->composed,
            // Both halves of the deal, in the player's words: what it buys and
            // what it costs. The forecast below already carries the edge as an
            // itemized part, so the two readings can never disagree.
            'bargain' => $this->bargain,
            'forecast' => $this->forecast($conditions),
        ];
    }

    /**
     * What this card costs in difficulty, quoted before it is chosen.
     *
     * A turn commits the instant it is submitted — there is no going back to
     * re-pick once the number turns out to have been 18 — so a card that does
     * not price itself is a card the player is guessing at. Every figure here
     * comes from the same Odds ledger the resolver will read, per stance, so
     * the forecast and the roll cannot drift apart.
     *
     * `conditions` is what is true RIGHT NOW: high ground already held counts,
     * a set-up beat the player is about to choose does not — that one is
     * quoted on its own card, as a grant, and the page adds it up as the plan
     * is assembled.
     *
     * @return array{rolls:bool,difficulty:int,band:string,parts:list<array{label:string,amount:int}>,stances:array<string,int>,bonus:int,bonus_parts:list<array{label:string,amount:int}>,grant:?array}
     */
    private function forecast(array $conditions): array
    {
        // The capability travels with the forecast because some of the ledger
        // prices the body, not the verb: a leap taken as a `cross` and a leap
        // taken as an `ascend` meet the same wind, and the card has to quote
        // what the resolver — which reads the stored card, capability and all —
        // is going to charge.
        $card = [
            'verb' => $this->verb,
            'risk' => $this->risk,
            'capability' => $this->capability,
            'target' => $this->target,
            'slot' => $this->slot->value,
            // The deal rides into the ledger the same way it will at
            // resolution: as one more itemized reason the number is what it is.
            'bargain' => $this->bargain,
        ];

        $grant = Odds::grant($this->verb);

        if (! Odds::rolls($this->verb)) {
            return [
                'rolls' => false,
                'difficulty' => 0,
                'band' => 'Certain',
                'parts' => [],
                'stances' => [],
                'bonus' => 0,
                'bonus_parts' => [],
                'grant' => $grant,
            ];
        }

        $stances = [];
        foreach (['balanced', 'cautious', 'bold'] as $stance) {
            $stances[$stance] = Odds::difficulty($card, $stance, $conditions)['value'];
        }

        $balanced = Odds::difficulty($card, 'balanced', $conditions);
        $bonus = Odds::bonus($conditions, $this->verb, $this->slot->value, $this->bargain['key'] ?? null);

        return [
            'rolls' => true,
            'difficulty' => $balanced['value'],
            'band' => Odds::band($balanced['value']),
            'parts' => $balanced['parts'],
            'stances' => $stances,
            'bonus' => $bonus['value'],
            'bonus_parts' => $bonus['parts'],
            'grant' => $grant,
        ];
    }

    public static function fromArray(array $data): self
    {
        return new self(
            slot: TurnSlot::from($data['slot']),
            verb: $data['verb'],
            label: $data['label'],
            description: $data['description'],
            target: $data['target'] ?? null,
            capability: $data['capability'] ?? null,
            risk: $data['risk'] ?? 'safe',
            cost: $data['cost'] ?? [],
            modifiers: $data['modifiers'] ?? [],
            composed: $data['composed'] ?? false,
            bargain: $data['bargain'] ?? null,
        );
    }
}
