<?php

namespace App\Game\Engine;

use App\Game\TurnSlot;

/**
 * A pre-validated verb + target + modifier bundle. Cards are generated by
 * the CardComposer from the current scene — never hand-listed, never free
 * text. The id is deterministic so a submission can be checked against the
 * stored offer.
 */
class ActionCard
{
    /**
     * @param  array{type:string,id:int|null,name:string}|null  $target
     * @param  list<array{meter:string,amount:int}>  $cost
     * @param  list<array{key:string,label:string,options:list<array{value:string,label:string}>}>  $modifiers
     */
    public function __construct(
        public readonly TurnSlot $slot,
        public readonly string $verb,
        public readonly string $label,
        public readonly string $description,
        public readonly ?array $target = null,
        public readonly ?string $capability = null,
        public readonly string $risk = 'safe', // safe | risky | degraded
        public readonly array $cost = [],
        public readonly array $modifiers = [],
        public readonly bool $composed = false,
    ) {}

    public function id(): string
    {
        return substr(hash('sha256', implode('|', [
            $this->slot->value,
            $this->verb,
            $this->capability ?? '-',
            $this->target['type'] ?? '-',
            $this->target['id'] ?? '-',
            $this->risk,
        ])), 0, 16);
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id(),
            'slot' => $this->slot->value,
            'verb' => $this->verb,
            'label' => $this->label,
            'description' => $this->description,
            'target' => $this->target,
            'capability' => $this->capability,
            'risk' => $this->risk,
            'cost' => $this->cost,
            'modifiers' => $this->modifiers,
            'composed' => $this->composed,
        ];
    }

    public static function fromArray(array $data): self
    {
        return new self(
            slot: TurnSlot::from($data['slot']),
            verb: $data['verb'],
            label: $data['label'],
            description: $data['description'],
            target: $data['target'] ?? null,
            capability: $data['capability'] ?? null,
            risk: $data['risk'] ?? 'safe',
            cost: $data['cost'] ?? [],
            modifiers: $data['modifiers'] ?? [],
            composed: $data['composed'] ?? false,
        );
    }
}
